name: ci
on:
  pull_request:
  release:
    types: [ published ]
  push:
    tags:
    branches:
      - main
      - develop

env:
  # Conan cache environment variables
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      # Recommendations:
      #   * support at least 2 operating systems
      #   * support at least 2 compilers
      #   * make sure all supported configurations for your project are built
      #
      # Disable/enable builds in this list to meet the above recommendations
      # and your own projects needs
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        compiler:
          - llvm-19
          - gcc
        generator:
          - "Ninja Multi-Config"
        build_type:
          - Release
          - Debug
        exclude:
          # GCC on both Windows and Mac are not supported
          - os: windows-latest
            compiler: gcc
        include:
          # Windows msvc builds
          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Debug

          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Release


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          ninja: true
          conan: 2.0.14
          vcpkg: false
          ccache: true
          cppcheck: true
          gcovr: true
          opencppcoverage: true

      - name: Install Conan Configuration
        run: |
          conan config install ./conan/settings.yml

      - name: Detect Conan Profile
        if: ${{ matrix.os == 'windows-latest' && matrix.compiler == 'msvc' }}
        run: |
          conan profile detect --force

      - name: Run Conan Install (windows-latest MSVC)
        if: ${{ matrix.os == 'windows-latest' && matrix.compiler == 'msvc' }}
        run: |
          conan install . --output-folder=./build -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True -s compiler.cppstd="20" --build=missing

      - name: Run Conan Install (ubuntu-latest LLVM or windows-latest LLVM)
        if: ${{ (matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest') && matrix.compiler == 'llvm-19' }}
        run: |
          conan install . --output-folder=./build -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True --build=missing -pr ./conan/profiles/llvm19 -s build_type=${{ matrix.build_type }} -s os=${{ matrix.os }}

      - name: Run Conan Install (ubuntu-latest GCC)
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc' }}
        run: |
          conan install . --output-folder=./build -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True --build=missing -pr ./conan/profiles/gcc14 -s build_type=${{ matrix.build_type }} --profile:build=./conan/profiles/gcc14

      - name: Configure CMake (windows-latest MSVC)
        if: ${{ matrix.os == 'windows-latest' && matrix.compiler == 'msvc' }}
        run: |
          cmake --preset conan-default

      - name: Configure CMake (Unix or windows-latest LLVM)
        if: ${{ matrix.os == 'ubuntu-latest' || (matrix.os == 'windows-latest' && matrix.compiler == 'llvm-19') }}
        run: |
          cmake --preset conan-release 

      - name: Build
        run: |
          cmake --build ./build --preset conan-release

      - name: Run Unit Tests
        run: |
          ctest --test-dir build/test/ --output-on-failure
